rewards/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'), 
    path('rewardsapp/', include('rewardsapp.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

rewardsapp/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from . import views
from django.urls import path

app_name = 'rewardsapp'
urlpatterns = [
        
    path('employee_list/', views.employee_list, name = 'employee_list'),
    path('employee_new/', views.employee_new, name = 'employee_new'),
    path('employee/<int:employee_id>/edit/', views.employee_edit, name='employee_edit'),
    path('employee/<int:employee_id>/delete/', views.employee_delete, name='employee_delete'),

    path('reward_list/', views.reward_list, name = 'reward_list'),
    path('reward_new/', views.reward_new, name = 'reward_new'),
    path('reward/<int:reward_id>/edit/', views.reward_edit, name='reward_edit'),
    path('reward/<int:reward_id>/delete/', views.reward_delete, name='reward_delete'),

    path('employee_reward_list/<int:employee_id>', views.employee_reward_list, name = 'employee_reward_list'),
    path('employee_reward_new/<int:employee_id>', views.employee_reward_new, name = 'employee_reward_new'),
    path('employee_reward/<int:employee_id>/<int:reward_id>/delete/', views.employee_reward_delete, name='employee_reward_delete'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users.views import user_list, user_edit, user_new, user_delete

urlpatterns = [
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html')),

    # reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('user_list/', user_list, name='user_list'),
    path('<int:pk>/edit/', user_edit, name='user_edit'),
    path('user_create/', user_new, name='user_new'),
    path('<int:pk>/delete/', user_delete, name='user_delete'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ['username', 'password', 'first_name', 'last_name', 'email', 'is_superuser']

        widgets = {
            'password': forms.PasswordInput(),
        }

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        
        self.fields['is_superuser'].label = 'System Administrator'
        self.fields['is_superuser'].help_text = 'Administrators are able to add users.'

class UserFormUpdate(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'is_superuser', )

    def __init__(self, *args, **kwargs):
        super(UserFormUpdate, self).__init__(*args, **kwargs)
        
        self.fields['is_superuser'].label = 'System Administrator'
        self.fields['is_superuser'].help_text = 'Administrators are able to add users.'

users/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect

from users.forms import UserForm, UserFormUpdate

@login_required
@user_passes_test(lambda user: user.is_superuser)
def user_list(request):

    users = User.objects.all().order_by('-date_joined')

    return render(request, 'user_list.html', {'users': users})


@login_required
@user_passes_test(lambda user: user.is_superuser)
def user_edit(request,pk):
    user = get_object_or_404(User,pk=pk)

    if request.method == "POST":
        
        form = UserFormUpdate(request.POST, instance= user)

        if form.is_valid():

            user = form.save(commit=False)

            user.save()

            return redirect('user_list')

    else:
        form = UserFormUpdate(instance= user)

        return render(request, 'user_form.html', {'form': form})

@login_required
@user_passes_test(lambda user: user.is_superuser)
def user_new(request):

    if request.method == "POST":

        form = UserForm(request.POST)
        
        if form.is_valid():

            user = None

            if form.cleaned_data['is_superuser'] == True:

                user = User.objects.create_superuser(username=form.cleaned_data['username'],
                                                     email=form.cleaned_data['email'],
                                                     password=form.cleaned_data['password'],
                                                     first_name=form.cleaned_data['first_name'],
                                                     last_name=form.cleaned_data['last_name'],)
            else:
                user = User.objects.create_user(username=form.cleaned_data['username'],
                                                email=form.cleaned_data['email'],
                                                password=form.cleaned_data['password'],
                                                first_name=form.cleaned_data['first_name'],
                                                last_name=form.cleaned_data['last_name'],)

            user.save()

            return redirect('user_list')

    else:
        return render(request, 'user_form.html', {'form': UserForm()})

@login_required
@user_passes_test(lambda user: user.is_superuser)
def user_delete(request, pk):

    user = get_object_or_404(User, pk=pk)

    user.delete()

    return redirect('user_list')

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>

   {% load static %}

   <!-- Required meta tags -->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<body>
   
   <nav class="navbar navbar-expand-md navbar-dark navbar-fixed-top bg-dark">

      <a class="navbar-brand" href="{% url 'home' %}">Rewards Tracker</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
         aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">

         <span class="navbar-toggler-icon"></span>

      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">

         <ul class="navbar-nav">

            {% if request.user.is_authenticated %}

            <li class="nav-item">
               <a class="nav-link" href="{% url 'rewardsapp:employee_list' %}">Employees</a>

            </li>

            <li class="nav-item">
               <a class="nav-link" href="{% url 'rewardsapp:reward_list' %}">Rewards</a>

            </li>

            {% endif %}

            {% if request.user.is_superuser %}

            <li class="nav-item">
               <a class="nav-link" href="{% url 'user_list' %}">User Administration</a>
            </li>

            {% endif %}

         </ul>

         {% if request.user.is_authenticated %}

         <ul class="navbar-nav ml-auto">

            <li class="nav-item">

               <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true"
                  aria-expanded="false">

                  {{ request.user.username }}

               </a>

               <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">

                  <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>

                  <div class="dropdown-divider"></div>

                  <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>

               </div>
            </li>
         </ul>

         {% else %}

         <form class="form-inline ml-auto">

            <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log In</a>

         </form>

         {% endif %}

      </div>
   </nav>

   <div>

      {% block content %}
      {% endblock content %}

   </div>

   <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
   <script src="{% static 'js/popper.min.js' %}"></script>
   <script src="{% static 'js/bootstrap.min.js' %}"></script>

   {% block script %}
   {% endblock script %}

</body>

templates/client_list.html
{#<p><a href="{% url 'client_edit' client_pk=client.pk visit_id=visit.visit_id%}">Edit</a> | <a href="{% url 'client_delete' client.pk %}">Delete</a></p>#}

{% extends 'base.html' %}

{% block title %}Client List{% endblock title %}

{% block content %}
<div class="container">

    <h2>Client Information</h2>

    <a href="{% url 'rewardsapp:client_new' %}" class="btn btn-primary">Add Client</a>

    <br />
    <br />

    <div>
        <table class="table table-striped table-bordered table-hover" id="tbl">
            <thead>
                <tr class="bg-info">
                    <th>Actions</th>
                    <th>Name</th>
                    <th>Birth Date</th>
                    <th>Gender</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Zip Code</th>
                    <th>Email</th>

                </tr>
            </thead>

            <tbody>
            {% for client in clients %}
                <tr>
                    <td>
                        <a href="{% url 'rewardsapp:employee_edit' employee_id=employee.pk %}">Edit</a>
                        |
                        <a href="{% url 'rewardsapp:employee_reward_list' employee_id=employee.pk %}">Rewards</a>
                    </td>

                    <td>{{ employee.firstname }}  {{ employee.lastname }}</td>

                </tr>
             {% endfor %}
            </tbody>
        </table>

    </div>
</div>
{% endblock content %}

{% block script %}

{% load static %}

<link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">

<script src="{% static 'js/datatables.min.js' %}"></script>

<script>

    $(function(){

        $("#tbl").DataTable({
            "columnDefs":[
                {
                    "targets": [0], "searchable": false, "orderable": false
                }
            ]
        });

    });

</script>

{% endblock script %}

templates/employee_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Employee Form{% endblock title %}

{% block content %}

<div class="container">

    <h1>Employee</h1>

    <form method="POST">

        {% csrf_token %}

        <div class="form-row">
            <div class="form-group col-md-4 mb-0">
                {{ form.number|as_crispy_field }}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-4 mb-0">
                {{ form.firstname|as_crispy_field }}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-4 mb-0">
                {{ form.lastname|as_crispy_field }}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-4 mb-0">
                {{ form.active|as_crispy_field }}
            </div>
        </div>

        <button type="submit" class="save btn btn-primary">Save</button>

        {% if employee %}

        <a href="{% url 'rewardsapp:employee_delete' employee_id=employee.pk %}" class="btn btn-danger">Delete</a>

        {% endif %}

    </form>

</div>

{% endblock content %}

templates/employee_list.html
{% extends 'base.html' %}

{% block title %}Employee List{% endblock title %}

{% block content %}

<div class="container">

    <h2>Employee List</h2>

    <a href="{% url 'rewardsapp:employee_new' %}" class="btn btn-primary">Add Employee</a>

    <br />
    <br />

    <div>
        <table class="table table-striped table-bordered table-hover" id="tbl">
            <thead>
                <tr class="bg-info">
                    <th>Actions</th>
                    <th>Employee Number</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Active</th>
                </tr>
            </thead>

            <tbody>
                {% for employee in employees %}
                <tr>
                    <td>
                        <a href="{% url 'rewardsapp:employee_edit' employee_id=employee.pk %}">Edit</a>
                        |
                        <a href="{% url 'rewardsapp:employee_reward_list' employee_id=employee.pk %}">Rewards</a>
                    </td>

                    <td>{{ employee.number }}</td>
                    <td>{{ employee.firstname }}</td>
                    <td>{{ employee.lastname }}</td>
                    <td>{{ employee.active }}</td>

                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
</div>
{% endblock content %}

{% block script %}

{% load static %}

<link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">

<script src="{% static 'js/datatables.min.js' %}"></script>

<script>

    $(function () {

        $("#tbl").DataTable({
            "columnDefs": [
                {
                    "targets": [0], "searchable": false, "orderable": false
                }
            ]
        });

    });

</script>

{% endblock script %}

templates/employee_reward_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Reward Form{% endblock title %}

{% block content %}

<div class="container">

    <h1>Reward Assignment</h1>

    <form method="POST" class="col-md-4">

        {% csrf_token %}

        {{ form|crispy }}

        <button type="submit" class="save btn btn-primary">Save</button>

        {% if reward %}

        <a href="{% url 'rewardsapp:reward_delete' reward_id=reward.pk %}" class="btn btn-danger">Delete</a>

        {% endif %}

    </form>

</div>

{% endblock content %}

templates/employee_reward_list.html
{% extends 'base.html' %}

{% block title %}Employee Reward List{% endblock title %}

{% block content %}
<div class="container">

    <h2>{{ employee.firstname }} {{ employee.lastname }}'s Reward List</h2>

    <a href="{% url 'rewardsapp:employee_reward_new' employee_id=employee.pk %}" class="btn btn-primary">Add Reward</a>

    <br />
    <br />

    <div>
        <table class="table table-striped table-bordered table-hover" id="tbl">
            <thead>
                <tr class="bg-info">
                    <th>Actions</th>
                    <th>Employee</th>
                    <th>Reward</th>
                    <th>Description</th>
                </tr>
            </thead>

            <tbody>
                {% for reward in rewards %}
                <tr>
                    <td>
                        <a href="{% url 'rewardsapp:employee_reward_delete' employee_id=employee.pk reward_id=reward.pk %}">Delete</a>
                    </td>

                    <td>{{ employee.firstname }} {{ employee.lastname }}</td>
                    <td>{{ reward.name }}</td>
                    <td>{{ reward.description }}</td>

                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
</div>
{% endblock content %}

{% block script %}

{% load static %}

<link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">

<script src="{% static 'js/datatables.min.js' %}"></script>

<script>

    $(function () {

        $("#tbl").DataTable({
            "columnDefs": [
                {
                    "targets": [0], "searchable": false, "orderable": false
                }
            ]
        });

    });

</script>

{% endblock script %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}

<section class="jumbotron text-center">
   <div class="container">
      <h1 class="jumbotron-heading">Rewards Tracker</h1>
      <p class="lead text-muted">Enterprise employee rewards tracking system</p>

   </div>
</section>

<div class="container">
   <div class="row">

      {% if request.user.is_authenticated %}
      <div class=" col-md-4">

         <div class="card">
            <div class="card-body">
               <h5 class="card-title">Employees</h5>
               <p class="card-text">Manage Employees</p>
               <a href="{% url 'rewardsapp:employee_list' %}" class="btn btn-primary">Employees</a>
            </div>
         </div>
      </div>

      <div class=" col-md-4">
         <div class="card">
            <div class="card-body">
               <h5 class="card-title">Rewards</h5>
               <p class="card-text">Manage Reward Definitions</p>
               <a href="{% url 'rewardsapp:reward_list' %}" class="btn btn-primary">Rewards</a>
            </div>
         </div>
      </div>

      {% endif %}

      {% if request.user.is_superuser %}
      <div class=" col-md-4">
         <div class="card">
            <div class="card-body">
               <h5 class="card-title">User Administration</h5>
               <p class="card-text">Manage application users</p>
               <a href="{% url 'user_list' %}" class="btn btn-primary">User Administration</a>
            </div>
         </div>
      </div>
      {% endif %}

   </div>
</div>

{% endblock content %}

templates/reward_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Reward Form{% endblock title %}

{% block content %}

<div class="container">

    <h1>Reward</h1>

    <form method="POST">

        {% csrf_token %}

        <div class="form-row">
            <div class="form-group col-md-4 mb-0">
                {{ form.name|as_crispy_field }}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-4 mb-0">
                {{ form.description|as_crispy_field }}
            </div>
        </div>

        <button type="submit" class="save btn btn-primary">Save</button>

        {% if reward %}

        <a href="{% url 'rewardsapp:reward_delete' reward_id=reward.pk %}" class="btn btn-danger">Delete</a>

        {% endif %}

    </form>

</div>

{% endblock content %}

templates/reward_list.html
{% extends 'base.html' %}

{% block title %}Reward List{% endblock title %}

{% block content %}

<div class="container">

    <h2>Reward List</h2>

    <a href="{% url 'rewardsapp:reward_new' %}" class="btn btn-primary">Add Reward</a>

    <br />
    <br />

    <div>
        <table class="table table-striped table-bordered table-hover" id="tbl">
            <thead>
                <tr class="bg-info">
                    <th>Actions</th>
                    <th>Name</th>
                    <th>Description</th>
                </tr>
            </thead>

            <tbody>
                {% for reward in rewards %}
                <tr>
                    <td>
                        <a href="{% url 'rewardsapp:reward_edit' reward_id=reward.pk %}">Edit</a>
                    </td>

                    <td>{{ reward.name }}</td>
                    <td>{{ reward.description }}</td>

                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
</div>
{% endblock content %}

{% block script %}

{% load static %}

<link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">

<script src="{% static 'js/datatables.min.js' %}"></script>

<script>

    $(function () {

        $("#tbl").DataTable({
            "columnDefs": [
                {
                    "targets": [0], "searchable": false, "orderable": false
                }
            ]
        });

    });

</script>

{% endblock script %}

templates/user_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}User Form{% endblock title %}

{% block content %}

<div class="container">

  <h1>User</h1>

  <form method="post" class="form col-lg-4">

    {% csrf_token %}

    {{ form|crispy }}

    <button class="btn btn-primary" type="submit">Save</button>

  </form>

</div>

{% endblock content %}

templates/user_list.html
{% extends 'base.html' %}

{% block title %}User List{% endblock title %}

{% block content %}
<div class="container">
   
    <h2>User Information</h2>

    <a href="{% url 'user_new' %}" class="btn btn-primary">Add User</a>

    <br />
    <br />
    
    <div>
        <table class="table table-striped table-bordered table-hover" id="tbl">
            <thead>
                <tr class="bg-info">
                    <th>Actions</th>
                    <th>User Name</th>
                    <th>Name</th>
                    <th>Is Employee</th>
                </tr>
            </thead>

            <tbody>
            {% for user in users %}
                <tr>
                    <td>
                        <a href="{% url 'user_edit' pk=user.pk %}">Edit</a>
                        |
                        <a href="{% url 'user_delete' pk=user.pk %}"
                               onclick="return confirm('Are you sure you want to delete?')">Delete</a>
                    </td>

                    <td>{{ user.username }}</td>
                    <td>{{ user.first_name }} {{ user.last_name }}</td>
                    <td>{{ user.is_superuser }}</td>
                    
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
</div>
{% endblock content %}

{% block script %}

{% load static %}

<link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">

<script src="{% static 'js/datatables.min.js' %}"></script>

<script>

    $(function(){

        $("#tbl").DataTable({
            "columnDefs":[
                {
                    "targets": [0], "searchable": false, "orderable": false
                }
            ]
        });
        
    });

</script>

{% endblock script %}